### ISSUE TITLE
naming of section headings

### ISSUE THREAD

**Issue by madhavitippani** [LieberInstitute/spatialNAcUtils#3]
I feel like it's less confusing for readers/users to have the same section headings in both the manuscript and the docs here when following the package.
1. change `Preparing Images for Fiji` in http://research.libd.org/visiumStitched/articles/visiumStitched.html to `Preparing inputs to Fiji`
2. Give a section heading ` Stitching images with Fiji` to the video section in http://research.libd.org/visiumStitched/articles/visiumStitched.html under `Building a SpatialExperiment` 
3. Function names not consistent in manuscript and docs, `prep_fiji_coords()`,  `prep_fiji_image()` in docs and `prep_image_coords()`  in manuscript
4. Change the section heading from `parsing outputs from Fiji` to `Creating group level samples` or vice versa
5. Change the section heading from `Array coordinates` to ` Defining array coordinates`. Talk about the add_array_coords() function.
6. Match the individual capture area spot colours to the colours used by Svitlana in the figure (array A - yellow, array B- green, array C - red)  
7. Maybe number the main sections in http://research.libd.org/visiumStitched/articles/visiumStitched.html, when reading through the page the text size of the main and subheadings is not always visible and thereby confusing readers if  they are reading a new section or an existing section

**Comment by Nick-Eagles** [comment]
Thanks Maddy! I addressed everything except point 7, which I wasn't sure about. For me, both the table of contents and heading sizes delimit each section as expected
